// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // The CLI (migrate/studio) uses the DIRECT, non-pooled connection — Prisma
    // Migrate can't run through Supabase's pgbouncer pooler. The app itself
    // connects via the pooled DATABASE_URL through the driver adapter (prisma.ts).
    // Falls back to DATABASE_URL when DIRECT_URL isn't set. See docs/PRODUCTION_CUTOVER.md.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
